export default [
    {"paramName": "Id", "type": "integer", "required": true },
    {"paramName": "DateBegin", "type": "date YYYY-MM-DD", "required": false},
    {"paramName": "DateEnd", "type":"date YYYY-MM-DD", "required": false},
    {"paramName": "ListingFee", "type": "ref", "required": false, "refs": ["Package", "PackageSingle", "Single"]},
    {"paramName": "AdStatus", "type": "ref", "required": false, "refs": ["Free", "Highlight", "XL", "x2_1", "x2_7", "x5_1", "x5_7", "x10_1", "x10_7", "x15_1", "x15_7", "x20_1", "x20_7"]},
    {"paramName": "AvitoId", "type": "string", "required": false},
    {"paramName": "ManagerName", "type": "string", "required": false},
    {"paramName": "ContactPhone", "type": "string", "required": false},
    {"paramName": "Description", "type": "string", "required": true},
    {"paramName": "Images", "type": "tag","required": false, "tags": ["Image"], "atrs": ["url", "name"] },
    {"paramName": "VideoURL", "type": "string", "required": false},
    {"paramName": "ContactMethod", "type": "ref", "required": false, "refs": ["По телефону и в сообщениях", "По телефону"]},
    {"paramName": "Category", "type": "ref", "required": true, "refs": ["Квартиры"]},
    {"paramName": "Price", "type": "integer", "required": true},
    {"paramName": "OperationType", "type": "ref", "required": true, "refs": ["Продам"]},
    {"paramName": "BalconyOrLoggiaMulti", "type": "tag", "required": false, "tags": ["Option"], "refs": ["Балкон", "Лоджия"]},
    {"paramName": "MarketType", "type": "ref", "required": true, "refs": ["Новостройка"]},
    {"paramName": "HouseType", "type": "ref", "required": true, "refs": ["Кирпичный", "Панельный", "Блочный", "Монолитный", "Монолитно-кирпичный"]},
    {"paramName": "Floor", "type": "integer", "required": true},
    {"paramName": "Floors", "type": "integer", "required": true},
    {"paramName": "Rooms", "type": "ref", "required": true, "refs": ["Студия","1","2","3","4","5","6","7","8","9","10","11","12","13"]},
    {"paramName": "Square", "type": "interval", "required": true, "interval": ["10", "5000"]},
    {"paramName": "KitchenSpace", "type": "interval", "required": false, "interval": ["2", "100"]},
    {"paramName": "LivingSpace", "type": "interval", "required": false, "interval": ["5", "5000"]},
    {"paramName": "Status", "type": "ref", "required": true, "refs": ["Квартира", "Апартаменты"]},
    {"paramName": "ViewFromWindows", "type": "tag", "required": true, "tags": "Option",  "refs": ["Во двор", "На улицу", "На солнечную сторону"]},
    {"paramName": "PassengerElevator", "type": "ref", "required": false, "refs":["Нет","1","2","3","4"]},
    {"paramName": "FreightElevator", "type": "ref", "required": false, "refs":["Нет","1","2","3","4"]},
    {"paramName": "Courtyard", "type": "tag", "required": false, "tags": ["Option"], "refs": ["Закрытая территория", "Детская площадка", "Спортивная площадка"]},
    {"paramName": "Parking", "type": "tag", "required": false, "tags": ["Option"], "refs": ["Подземная", "Наземная многоуровневая", "Открытая во дворе", "За шлагбаумом во дворе"]},
    {"paramName": "RoomType", "type": "tag", "required": false, "tags": ["Option"], "refs": ["Изолированные", "Смежные"]},
    {"paramName": "BathroomMulti", "type": "tag", "required": false, "tags": ["Option"], "refs":["Совмещённый", "Раздельный"]},
    {"paramName": "SaleOptions", "type": "tag", "required": false, "tags": ["Option"], "refs":["Можно в ипотеку", "Продажа доли", "Аукцион"]},
    {"paramName": "CeilingHeight", "type": "float", "required": false},
    {"paramName": "NDAdditionally", "type": "tag", "required": false, "tags": ["Option"], "refs": ["Балкон", "Лоджия", "Гардеробная", "Панорамные окна"]},
    {"paramName": "NewDevelopmentId", "type": "string", "required": true, "comment": "New building object — object ID from the XML directory"},
    {"paramName": "DevelopmentsBuildingName", "type": "string", "required": false},
    {"paramName": "PropertyRights", "type": "ref", "required": true, "refs":["Собственник", "Посредник", "Застройщик"]},
    {"paramName": "Decoration", "type": "ref", "required": true, "refs":["Без отделки", "Предчистовая", "Чистовая"]},
    {"paramName": "SaleMethod", "type": "ref", "required": false, "refs":["Договор долевого участия", "Договор уступки права требования", "Договор ЖСК"]},
    {"paramName": "ShareholderFirstName", "type": "string", "required": false},
    {"paramName": "ShareholderLastName", "type": "string", "required": false},
    {"paramName": "ShareholderPatronymic", "type": "string", "required": false},
    {"paramName": "ShareholderINN", "type": "integer", "required": false}
]