export default [
    {id: 1, erroCode: "err1", errorCode: "/api/set-feed - data/controller", comment: "invalid file or path"},
    {id: 2, erroCode: "err2", errorCode: "/api/set-feed - data/controller", comment: "invalid format file"},
    {id: 3, erroCode: "err3", errorCode: "/api/set-feed - data/controller", comment: "Not bearer token at headers"},
    {id: 4, erroCode: "err4", errorCode: "/api/set-feed - data/controller", comment: "Invalid bearer token"},
    {id: 5, erroCode: "err5", errorCode: "/api/set-feed - data/controller", comment: "Error saved file"},
    {id: 6, erroCode: "err6", errorCode: "/api/set-feed - data/servive", comment: "Error path file"},
    {id: 7, erroCode: "err7", errorCode: "/api/set-feed - data/servive", comment: "Error removed file"},
    {id: 8, erroCode: "err8", errorCode: "/api/set-feed - avito/save/servive", comment: "Error saved file"},
    {id: 9, erroCode: "err9", errorCode: "/api/set-feed - data/servive", comment: "Error saved file"},
    {id: 10, erroCode: "err10", errorCode: "/api/set-feed - check/servive", comment: "invalid data"},  
    {id: 11, erroCode: "err11", errorCode: "/api/set-feed - check/servive", comment: "errorsStr"},
    {id: 12, erroCode: "err12", errorCode: "/api/set-feed - auth/midleware", comment: "not token"},
    {id: 13, erroCode: "err13", errorCode: "/api/set-feed - auth/midleware", comment: "invalid token"},  
    {id: 14, erroCode: "err14", errorCode: "/api/set-feed - auth/midleware", comment: "not auth"},  
    {id: 15, erroCode: "err15", errorCode: "/api/set-feed - data/service", comment: "obj.Ads.Ad is object"},
    {id: 16, erroCode: "err16", errorCode: "/api/set-feed - data/controler", comment: "invalid body req"},
    {id: 17, erroCode: "err17", errorCode: "/api/get-feed - getData/service", comment: "Error get date"},
    {id: 18, erroCode: "err18", errorCode: "/api/get-feed - getData/service", comment: "Error get date"},      
    {id: 19, erroCode: "err19", errorCode: "/api/get-feed - getData/service", comment: "Invalid data user at req"},
    {id: 20, erroCode: "err20", errorCode: "/api/get-feed - getData/service", comment: "Error paginate"},
    {id: 21, erroCode: "err21", errorCode: "/api/update-feed - avito/update/service", comment: "Invalid req body or path to file"}, 
    {id: 22, erroCode: "err22", errorCode: "/api/update-feed - avito/update/service", comment: "Error read file"},
    {id: 23, erroCode: "err23", errorCode: "/api/update-feed - avito/update/service", comment: "Error read file return error at module"},
    {id: 24, erroCode: "err24", errorCode: "/api/update-feed - avito/update/service", comment: "Error updated date objects"}, 
    {id: 25, erroCode: "err25", errorCode: "/api/update-feed - avito/update/service", comment: "Error updated date objects"}, 
    {id: 26, erroCode: "err26", errorCode: "/api/update-feed - avito/update/service", comment: "Error wrated data"}, 
    {id: 27, erroCode: "err27", errorCode: "/api/update-feed - avito/check/service", comment: "Error cheking"},
    {id: 28, erroCode: "err28", errorCode: "/api/update-feed - avito/update/service", comment: "Error cheking"},
    {id: 29, erroCode: "err29", errorCode: "/api/update-feed - avito/cheack/service", comment: "Error cheking"},
    {id: 30, erroCode: "err30", errorCode: "/api/update-feed - avito/cheack/service", comment: "Error cheking values"},
    {id: 31, erroCode: "err31", errorCode: "/api/update-feed - avito/cheack/service", comment: "invalid tegs"},
] 